# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: "Azure Pipelines"

variables:
- name: CloudInitContent

steps:

- script: |
    echo $(CloudInitContent)

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(f8ee07ed-b563-4b27-931f-56bdf1405242)'
    subscriptionId: 'f8ee07ed-b563-4b27-931f-56bdf1405242'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Devoir2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/AzureResourceGroup1/AzureResourceGroup1/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/AzureResourceGroup1/AzureResourceGroup1/azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'