# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: "Azure Pipelines"

variables:
  - name: CloudInitContent
  - name: AzureAppInfrastructure
    value: 'AzureResourceGroup1\AzureResourceGroup1'

- stage: Infra
  displayName: Infrastructure Deployment
  jobs:
  - job: Infra
    displayName: Infrastructure Deployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: ARM Template Deployment
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure subscription 1(970fcef5-9c23-4f7d-a11b-5a96d104f066)'
        subscriptionId: '970fcef5-9c23-4f7d-a11b-5a96d104f066'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: '$(rgLocation)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)\$(AzureAppInfrastructure)\azuredeploy.json'
        csmParametersFile: '$(Build.SourcesDirectory)\$(AzureAppInfrastructure)\azuredeploy.parameters.json'
        overrideParameters: '-name $(AzureFunctionAppName) -resourceGroup $(resourceGroupName)'
        deploymentMode: 'Incremental'
